### ISSUE TITLE
Wrong message displayed in case payment amount greater than wallet amount

### ISSUE THREAD

**Issue by anmol-pabla** [cs253-team2/frontend#63]
In case the amount to be cleared as dues or the amount for instant payment is more than the current wallet amount, the transaction shouldn't occur. However, the portal throws a Transaction Completed Successfully Dialogue box.

The transaction is not processed by the portal as expected, but the message displayed to the user is of conflicting nature.

**Comment by Prathamsahu52** [comment]
Fixed in merge #69
