### ISSUE TITLE
Lack of information regarding password format

### ISSUE THREAD

**Issue by anmol-pabla** [cs253-team2/frontend#64]
The portal expects the passwords to have capital letters along with other characters like special symbols for improved security. However, the user is not informed through the portal of the need to include a capital letter in their password, which can leave the user confused about the reason for password invalidity.

The placeholder for the password field is `abcxyz@123`. This also doesn't include a capital letter as expected by the portal.

**Comment by Prathamsahu52** [comment]
Fixed on merge request #68
